
postprocessors:
  args:
    DistributionPostProcess:
      edl: false
      lidar_range: &lr [-50, -50, -5, 50, 50, 3]
      voxel_size: &voxel_size [0.2, 0.2, 0.2]
      visualization: false
      stride:
        object: 2
        surface: 2
      distr_r:
        object: 2.0
        surface: 2
  test: [ 'DistributionPostProcess' ]

vis_function: false
metrics:
  MetricDynamicIou:
    lidar_range: *lr
    voxel_size: *voxel_size
    stride: 2